logo: '/assets/img/musa-logo.png'
description: The collaborative 30-Days of Maps Challenge entries from the MUSA program
author: Masters of Urban Spatial Analytics
day_categories:
  '2024':
    '1': Points
    '2': Lines
    '3': Polygons
    '4': A bad map
    '5': Analog Map
    '6': Asia
    '7': Navigation
    '8': Africa
    '9': Hexagons
    '10': North America
    '11': Retro
    '12': South America
    '13': Choropleth
    '14': Europe
    '15': OpenStreetMap
    '16': Oceania
    '17': Flow
    '18': Atmosphere
    '19': 5-minute map
    '20': Outdoors
    '21': Raster
    '22': North is not always up
    '23': 3D
    '24': Black & white
    '25': Antarctica
    '26': Minimal
    '27': Dot
    '28': Is this a chart or a map?
    '29': Population
    '30': My favorite...
  '2023':
    '1': Points
    '2': Lines
    '3': Polygons
    '4': A bad map
    '5': Analog map
    '6': Asia
    '7': Navigation
    '8': Africa
    '9': Hexagons
    '10': North America
    '11': Retro
    '12': South America
    '13': Choropleth
    '14': Europe
    '15': OpenStreetMap
    '16': Oceania
    '17': Flow
    '18': Atmosphere
    '19': 5-minute map
    '20': Outdoors
    '21': Raster
    '22': North is not always up
    '23': 3D
    '24': Black & white
    '25': Antarctica
    '26': Minimal
    '27': Dot
    '28': Is this a chart or a map?
    '29': Population
    '30': '"My favorite..."'
